language: node_js
node_js:
- "9"
# Cache node_modules between builds
cache:
  directories:
  - "node_modules"
# Build website
script: npm run build
# Deploy master to gh-pages branch
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: build
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
